#! /bin/sh
#
### BEGIN INIT INFO
# Provides: cyrus-imapd-2.4.17
# Required-Start: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: common init system for cyrus 2.4.17 IMAP/POP3 daemons.
# Description: common init system the for cyrus 2.4.17 IMAP/POP3 daemons.
#              starts the central cyrus 2.4.17 master process, which can 
#              then start various services depending on configuration.
#              Typically starts IMAP and POP3 daemons, but might also
#              start an NNTP daemon and various helper daemons for
#              distributed mail/news storage systems (high-performance
#              and/or high-reliability setups).
### END INIT INFO
#
#		Copyright 2001-2005 by Henrique de Moraes Holschuh <hmh@debian.org>
#		Various modifications done by Sven Mueller <debian@incase.de>
#		Distributed under the GPL version 2
#

# Make sure we get sane results on borked locales
LC_ALL=C
export LC_ALL

# Overridable defaults
unset CYRUS_VERBOSE
unset LISTENQUEUE
unset CONF
unset MASTERCONF
[ -r /etc/default/cyrus-imapd ] && . /etc/default/cyrus-imapd

[ "x${CYRUS_VERBOSE}" != "x" ] && export CYRUS_VERBOSE
# Make sure the master process is daemonized
OPTIONS="${OPTIONS} -d"
[ "x${CONF}" != "x" ] && OPTIONS="-C ${CONF} ${OPTIONS}"
[ "x${MASTERCONF}" != "x" ] && OPTIONS="-M ${MASTERCONF} ${OPTIONS}"
[ "x${LISTENQUEUE}" != "x" ] && OPTIONS="-l ${LISTENQUEUE} ${OPTIONS}"

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/lib/cyrus/bin
DAEMON=/usr/lib/cyrus/bin/master
NAME=cyrus-master
PIDFILE="/var/run/${NAME}.pid"
#touch /var/run/${NAME}.pid
DESC="Cyrus IMAPd"

set -e

START="--start --quiet --pidfile ${PIDFILE} --exec ${DAEMON} --name ${NAME} -- ${OPTIONS}"

verifydb() {
   while read -r DBKEY DBVALUE ; do
	match=`sort -u < $1 | gawk "/^${DBKEY}[[:blank:]]/ { print \\$2 }"`
	[ "x${match}" != "x${DBVALUE}" ] && return 0
   done
   return 1
}

createdir() {
# $1 = user
# $2 = group
# $3 = permissions (octal)
# $4 = path to directory
	[ -d "$4" ] || mkdir -p "$4"
	chown -c -h "$1:$2" "$4"
	chmod -c "$3" "$4"
}

check_status () {
	if [ "$1" = "verbose" ]; then
		PRINTIT=echo
	else
		PRINTIT=true 
	fi
	if [ ! -f ${PIDFILE} ]; then
		# using [c] in the grep avoids catching the grep 
		# process itself
		if ps auxww | grep -qE 'usr/lib/cyrus/bin/master' ; then
			# Damn, PID file doesn't exist, but cyrmaster process
			# exists. Though strictly speaking, we should not
			# do this, reconstruct the PID file here.
			pidof /usr/lib/cyrus/bin/master > /dev/null 2>&1 \
			&& pidof /usr/lib/cyrus/bin/master > ${PIDFILE}
			${PRINTIT} "cyrus master running with PID `cat ${PIDFILE}`"
			return 0
		fi
	fi	
	if [ -s ${PIDFILE} ] && kill -0 `cat ${PIDFILE}` > /dev/null 2>&1; then
		${PRINTIT} "cyrus master running with PID `cat ${PIDFILE}`"
		return 0
	else
		# the PID file might simply not match the cyrmaster process.
		if pidof /usr/lib/cyrus/bin/master > /dev/null 2>&1 ; then
			# go ahead and fix it
			pidof /usr/lib/cyrus/bin/master > ${PIDFILE}
			${PRINTIT} "cyrus master running with PID `cat ${PIDFILE}`"
			return 0
		else
			# no process and/or no PID file, return failure
			${PRINTIT} "cyrus master not running with"
			return 1
		fi
	fi
	# this point should never be reached, return unknown status if it 
	# is anyway
	return 4
}

case "$1" in
  start)
	echo -n "Starting ${DESC}: "
#	if check_status ; then
#		echo "${DAEMON} already running."
#		exit 0
#	fi
	if start-stop-daemon ${START} >/dev/null 2>&1 ; then
		echo "$NAME."
	else
		if ! check_status ; then
			echo "(failed)."
			exit 1
		fi
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		--name ${NAME} --quiet --startas $DAEMON >/dev/null 2>&1 ; then
		echo "$NAME."
		rm -f ${PIDFILE}
		kill `pidof /usr/lib/cyrus/bin/master`
		exit 0
	else
		# process running?
		if check_status; then
			# Yes, report failure.
			echo "."
			kill `pidof /usr/lib/cyrus/bin/master`
			exit 1
		else
			# No, return as if stopped a running process 
			# successfully.
			echo "."
			rm -f ${PIDFILE}
			exit 0
		fi
	fi
	;;
  reload|force-reload)
	echo "Reloading $DESC configuration files."
	if start-stop-daemon --stop --signal 1 --quiet \
		--name ${NAME} --pidfile /var/run/$NAME.pid >/dev/null 2>&1 ; then
		exit 0
	else
		exit 1
	fi
  	;;
  restart)
  	$0 stop && {
	  echo -n "Waiting for complete shutdown..."
	  i=5
	  while [ $i -gt 0 ] ; do
	  	# exit look when server is not running
	  	check_status || break
		sleep 2s
		i=$(($i - 1))
		echo -n "."
	  done
	  [ $i -eq 0 ] && {
	  	echo
		echo "fatal: incomplete shutdown detected, aborting."
		exit 1
	  }
	  echo
	}
	exec $0 start
	;;
  status)
  	check_status verbose
	exit $?
	;;
  try-restart)
  	check_status
	if [ "$?" -eq 0 ]; then
		exec $0 restart
	else
  		# LSB says to return 0 in try-restart if the service is
		# not running.
		exit 0
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|force-reload}" 1>&2
	exit 1
	;;
esac

exit 0
